version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/staticfiles
      - media:/app/media

  frontend:
    build: ./frontend/
    env_file: .env
    command: sh -c "cp /app/build/index.html /app/build/favicon.ico /app/build/manifest.json /app/build/robots.txt /app/build/asset-manifest.json /static/ 2>/dev/null; cp -r /app/build/static/* /static/"
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
