server_tokens off;

server {
  listen 80;
  index index.html;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://backend:8000;
  }
  
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://backend:8000;
  }
  
  location /media/ {
    alias /media/;
    expires 30d;
    add_header Cache-Control "public";
  }

  location /static/ {
    alias /static/;
    expires 30d;
    add_header Cache-Control "public";
  }

  location / {
    alias /static/;
    try_files $uri $uri/ /index.html;
  }
}